### ISSUE TITLE
Helping

### ISSUE THREAD

**Issue by binjospookie** [DracotMolver/Soube#3]
Hello! Do you need help to build your app for MacOS and Windows?
I'm a creator of --shots and I can help you.

**Comment by DracotMolver** [comment]
Hi, wow thanks for your message. Actually I'm working already on that lol. It was just a matter of time, you know...work sometimes takes you too much time of your life :P. I'm testing and adding features for windows right know (Windows 10 32/64 bits and Windows 7) and I was able to build it and install it successfully :). But, i will be happy to get any advice :). [**SOLVED**: Well, actually, just recently I'm adding thumbar buttons and I'm trying to hide the play button to show the pause and viceversa]. By the way...are you a navite spoken English? if so, i'd appreciate your help a lot...because I'm making a new brand website for the next version of the app :). Any help from my to you, just ask me :)

**Comment by binjospookie** [comment]
I'm not a native speaker :disappointed:  
If you'll need helping, just ask me :smile:
