### ISSUE TITLE
How can i run this project on windows?

### ISSUE THREAD

**Issue by hahazexia** [DracotMolver/Soube#4]
I input 'npm run build',then it stops at 'Downloading electron-v1.4.13-linux-ia32.zip',
Why is linux? I just run it on windows?
And the download is always failed.

**Comment by DracotMolver** [comment]
Hi. You have to run `npm run dist`, this will generate the proper installer of the OS you are using. By default Electron will look for a `dist` forlder which you have to create at root.

```
/-app
/-build
/-dist
/-package.json
```
Pay attention to this part of the `package.json`

```
"scripts": {
    "pack": "build --dir", // This is not useful now :/
    "dist": "build", // This will run the build section of the package.json which will creates Win, Mac and Linux (.deb and .rpm) installer.
    "build": "electron-packager ./app soube --out=dist --platform=linux --ignore='^/dist$' --arch=all --prune --icon='./app/assets/img/icon.png'" // This part is LINUX only, this will generate the project as a binary folder for distributions that doesn't support .deb or .rpm
  }
```

The process can take a while so don't worry about it, but to be sure take a look at the dist folder and you will see: `win`, `win-unpacked` and a `NSIS` installer wich will be then a `soube Setup 1.3.3.exe`.

In this repo I have two branch `master` and `develop`. Don't use the develop because I'm changing the structure of the folder, refactoring the code, fixing some stuff and adding new ones :)... and it is still unstable.
